language: node_js

node_js:
  - 7
  - 6

cache:
  directories:
    - node_modules

install:
  - npm i -g npm@latest
  - npm install

script:
  - npm run test
  - npm run lint
  - npm run prebuild
  - npm run build